version: '2'
services:
    jhipsterfirstapplication-app:
        image: jhipsterfirstapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterfirstapplication-mysql:3306/jhipsterfirstapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterfirstapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterfirstapplication-mysql
